# Generated by Django 4.1.5 on 2023-02-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_wishlist',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
