# Generated by Django 4.1.5 on 2023-04-03 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderproduct_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing', models.CharField(blank=True, max_length=30)),
                ('p_date', models.DateTimeField(blank=True, null=True)),
                ('accepted', models.CharField(blank=True, max_length=30)),
                ('a_date', models.DateTimeField(blank=True, null=True)),
                ('out_delivery', models.CharField(blank=True, max_length=30)),
                ('out_date', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.CharField(blank=True, max_length=20)),
                ('d_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled', models.CharField(blank=True, max_length=30)),
                ('c_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderproduct')),
            ],
        ),
    ]
