# Generated by Django 4.1.5 on 2023-04-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_ordertracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertracking',
            name='p_date',
        ),
        migrations.RemoveField(
            model_name='ordertracking',
            name='processing',
        ),
    ]
